apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3N3b3Jk  # rootpassword
  mysql-database: d29yZHByZXNz  # wordpress
  mysql-user: d29yZHByZXNz  # wordpress
  mysql-password: d29yZHByZXNzcGFzcw==  # wordpresspass
  wordpress-db-password: d29yZHByZXNzcGFzcw==  # wordpresspass