apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  mysql-root-password: {{ .Values.secret.mysqlRootPassword }}
  mysql-database: {{ .Values.secret.mysqlDatabase }}
  mysql-user: {{ .Values.secret.mysqlUser }}
  mysql-password: {{ .Values.secret.mysqlPassword }}
  wordpress-db-password: {{ .Values.secret.wordpressDbPassword }}