apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-wordpress-service
spec:
  selector:
    app: {{ .Release.Name }}-wordpress
  ports:
  - port: {{ .Values.wordpress.port }}
    targetPort: {{ .Values.wordpress.port }}
  type: ClusterIP